name = "Hugo Initio"
license = "MIT"
licenselink = "https://github.com/WindAflame/hugo-initio/blob/master/LICENSE.md"
description = ""
homepage = "https://WindAflame.github.io/hugo-initio/"
tags = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
features = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
min_version = "0.1"

[author]
  name = "Endy WindAflame"
  homepage = "https://ewa-blog.netlify.com/"

[original]
  name = "Hugo Initio"
  author = "Miguel Simoni"
  homepage = "http://www.gettemplate.com/info/initio/"
  repo = "https://miguelsimoni.github.io/"
