baseURL = "/"
languageCode = "en-us"
title = "Initio - Free, multipurpose html5 template by GetTemplate"
theme = "hugo-initio"
publishDir = "public"

[params]
    avatar = "avatar_man.png"
    name = "Endy WindAflame"
    description = "A mystery person"
    email = "endy.windaflame@example.com"
    phone = "+234 23 9873237"
    address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2017
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.section.header]
    enableEmail = true
    enableFollowme = true

[params.section.subheader]
    show = true
    text = 'Let me tell you something my friend. hope is a dangerous thing. hope can drive a man insane. you <a href="#">measure</a> yourself by the people who measure themselves by you. it only took me <a href="#">six days</a>.'

[params.section.service]
    show = true
    title = "Services"

[params.section.recentworks]
    show = true
    title = "Recent Works"

[params.section.download]
    show = true

[params.section.clients]
    show = true
    title = "Clients"

[params.section.upperfooter]
    show = true
    enableContact = true
    enableFollowme = true
    enableTextWidget = true
    enableFormWidget = true

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "youtube"
	url = "http://www.youtube.com/"
    icon = "fa-youtube-play"
    header = true
    footer = false
    sharethis = true
    network = "youtube"
[[params.social]]
	title = "twitch"
	url = "http://www.twitch.com/"
    icon = "fa-twitch"
    header = true
    footer = false
    sharethis = true
    network = "twitch"
[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nickname"
    icon = "fa-facebook-square"
    header = true
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/nickname"
    icon = "fa-twitter-square"
    header = true
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fa-instagram"
    header = true
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fa-google-plus-square"
    header = true
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fa-linkedin-square"
    header = true
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fa-tumblr-square"
    header = true
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/nickname"
    icon = "fa-github"
    header = true
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fa-envelope"
    header = false
    footer = false
    sharethis = true
    network = "email"
